#=========================== Wechat-Api App =============================
app:
  name: "wechat-api"

#============================== Server ==================================

server:
  port: 8080

#============================== Database ==================================
datebase:
  type: "mysql"